[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
evm_version = 'london'
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    '@chainlink/contracts/=node_modules/@chainlink/contracts'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
